from django.conf.urls.defaults import *
from my import views
from my import admin
from my import settings
import os.path



urlpatterns = patterns('',
    ('^hello/$', views.hello),
    (r'^sc/$', views.sc),
    (r'^db/$', views.db),
    (r'^login$', admin.login),
    (r'^testchmod/$', admin.testchmod),
    (r'^job_wd/$', admin.job_wd),
    (r'^job_huifu/$', admin.job_huifu),
    (r'^job_dan/$', admin.job_dan),
    (r'^tj_wd/$', admin.tj_wd),
    (r'^wodfanadduser/$', admin.wodfanadduser),
    (r'^wodfanuserlist/$', admin.wodfanuserlist),
    (r'^wodfaninsertuser/$', admin.wodfaninsertuser),
    (r'^getdapei/$', admin.getdapei),
    (r'^getrenwu/$', admin.getrenwu),
    (r'^tj_ft/$', admin.tj_ft),
    (r'^job_ft/$', admin.job_ft),
    (r'^tj_dr/$', admin.tj_dr),
    (r'^job_dr/$', admin.job_dr),
    (r'^fuckst/$', admin.fuckst),
    (r'^ftscore/$', admin.ftscore),
    (r'^drscore/$', admin.drscore),
    (r'^gettouxiang/$', admin.gettouxiang),
    (r'^setyonghu/$', admin.setyonghu),
    (r'^yiyonghu/$', admin.yiyonghu),
    (r'^tuiuser/$', admin.tuiuser),
    (r'^qtuiuser/$', admin.qtuiuser),
    (r'^getmabi/$', admin.getmabi),
    (r'^getmabi1/$', admin.getmabi1),
    (r'^getmabi2/$', admin.getmabi2),
    (r'^getmabi3/$', admin.getmabi3),
    (r'^wenda/$', admin.wenda),
    (r'^daren/$', admin.daren),
    (r'^chenqa/$', admin.chenqa),
    (r'^quchenqa/$', admin.quchenqa),
    (r'^chendaren/$', admin.chendaren),
    (r'^quchendaren/$', admin.quchendaren),
    (r'^updateform1/$', admin.updateform1),
    (r'^bufenlei/$', admin.bufenlei),
    (r'^upbufenlei/$', admin.upbufenlei),
    (r'^updateform2/$', admin.updateform2),
    (r'^updateform3/$', admin.updateform3),
    (r'^updateform4/$', admin.updateform4),
    (r'^updateform5/$', admin.updateform5),
    (r'^updateform6/$', admin.updateform6),
    (r'^fllist/$', admin.fllist),
    (r'^shoupei/$', admin.shoupei),
    (r'^zilist/$', admin.zilist),
    (r'^addzi/$', admin.addzi),
    (r'^insertzi/$', admin.insertzi),
    (r'^delzi/$', admin.delzi),
    (r'^editzi/$', admin.editzi),
    (r'^updatezi/$', admin.updatezi),
    (r'^addfl/$', admin.addfl),
    (r'^insertfl/$', admin.insertfl),
    (r'^delfl/$', admin.delfl),
    (r'^editfl/$', admin.editfl),
    (r'^updatefl/$', admin.updatefl),
    (r'^checkcode/$', admin.checkcode),
    (r'^checklogin/$', admin.checklogin),
    (r'^page/$', views.page),
    (r'^see/$', views.see),
    (r'^excel/$', admin.excel),
    (r'^fengpi/$', admin.fengpi),
    (r'^md5/$', views.md5),
    (r'^zip/$', views.zip),
    (r'^copy/$', views.copy),
    (r'^down/$', admin.down),
    (r'^zhualog/$', admin.zhualog),
    (r'^bianlog/$', admin.bianlog), 
    (r'^qudan/$', admin.qudan),
    (r'^xianshimag/$', admin.xianshimag),
    (r'^guanbimag/$', admin.guanbimag),
    (r'^pictpaixu/$', admin.pictpaixu),
    (r'^jsontest/$', admin.jsontest),
    (r'^updatepict/$', admin.updatepict),
    (r'^down2/$', admin.down2),
    (r'^$', admin.index),
    (r'^xiupian$', admin.xiupian),
    (r'^insertdtuijian/$', admin.insertdtuijian),
    (r'^yidan/$', admin.yidan),
    (r'^pass$', admin.pass1),
    (r'^kongzhi/$', admin.kongzhi),
    (r'^shedai/$', admin.shedai),
    (r'^shandai/$', admin.shandai),
    (r'^tipai/$', admin.tipai),
    (r'^updatedapei/$', admin.updatedapei),
    (r'^del$', admin.del1),
    (r'^dahui$', admin.dahui),
    (r'^pidahui$', admin.pidahui),
    (r'^upload/$', admin.upload),
    (r'^sback/$', admin.sback),
    (r'^tongguo/$', admin.tongguo),
    (r'^uploadfy/$', admin.uploadfy),
    (r'^uploadfy1/$', admin.uploadfy1),
    (r'^pipass$', admin.pipass),
    (r'^pipassc10d$', admin.pipassc10d),
    (r'^pidahui$', admin.pidahui),
    (r'^chongshen/$', admin.chongshen),
    (r'^chongshenq/$', admin.chongshenq),
    (r'^tuipict/$', admin.tuipict),
    (r'^feed/$', admin.feed),
    (r'^pidel$', admin.pidel),
    (r'^kaiqi/$', admin.kaiqi),
    (r'^guanbi/$', admin.guanbi),
    (r'^budapei/$', admin.budapei),
    (r'^fenpeix$', admin.fenpeix),
    (r'^logout$', admin.logout),
    (r'^fenpeib$', admin.fenpeib),
    (r'^pixiu$', admin.pixiu),
    (r'^insertpict/$', admin.insertpict),
    (r'^qupict/$', admin.qupict),
    (r'^shouquan/$', admin.shouquan),
    (r'^c10/$', admin.c10),
    (r'^c11/$', admin.c11),
    (r'^c10d/$', admin.c10d),
    (r'^c11d/$', admin.c11d),
    (r'^pibei$', admin.pibei),
    (r'^pipass1$', admin.pipass1),
    (r'^pipass2$', admin.pipass2),
    (r'^mag/$', admin.maglist),
    (r'^chen/$', admin.chen),
    (r'^quchen/$', admin.quchen),
    (r'^pictlist/$', admin.pictlist),
    (r'^yipictlist/$', admin.yipictlist),
    (r'^weipictlist/$', admin.weipictlist),
    (r'^delmag$', admin.delmag),
    (r'^delpict/$', admin.delpict),
    (r'^showallimg/$', admin.showallimg),
    (r'^addmag/$', admin.addmag),
    (r'^editmag/$', admin.editmag),
    (r'^editpict/$', admin.editpict),
    (r'^updatemag/$', admin.updatemag),
    (r'^yidapei/$', admin.yidapei),
    (r'^qudapei/$', admin.qudapei),
    (r'^blog/$', admin.blog),
    (r'^tuiblog/$', admin.tuiblog),
    (r'^yiblog/$', admin.yiblog),
    (r'^qublog/$', admin.qublog),
    (r'^pictorial/$', admin.pictorial),
    (r'^tuidapei/$', admin.tuidapei),
    (r'^beijing$', admin.beijing),
    (r'^insertmag$', admin.insertmag),
    (r'^x/$', admin.x),
    (r'^setindex/$', admin.setindex),
    (r'^setdapei/$', admin.setdapei),
    (r'^setindexupdate/$', admin.setindexupdate),
    (r'^setdapeiupdate/$', admin.setdapeiupdate),
    (r'^judge/$', admin.judge),
    (r'^xx/$', admin.xx),
    (r'^xb/$', admin.xb),
    (r'^b/$', admin.b),
    (r'^test/$', views.test),
    #(r'^upload/$', admin.upload),
    #(r'^upload1/$', admin.upload1),
    (r'^123.html/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_PATH}),
    ('^time/$', views.current_datetime),
    (r'^getc/(\d{4})/(\d{2})/$',views.getc),
    (r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.dirname(globals()["__file__"])+'/css'}),
    (r'^img/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.dirname(globals()["__file__"])+'/img'}),
    (r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.dirname(globals()["__file__"])+'/js'}),
    #(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.dirname(globals()["__file__"])+'/images'}),
    (r'^zip/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.dirname(globals()["__file__"])+'/zip'}),
    #(r'^images/(?P</path><path>.*)$', 'django.views.static.serve', {'document_root': '/var/www/django-demo/images'}),
    #(r'^images/(?P.*)$', 'django.views.static.serve',{'document_root': settings.STATIC_PATH}),
    (r'^images/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_PATH}),






)

